baseURL = "http://geekzonehosting.is-a-geek.com/"
publishdir = "c:/Hugo/Build/"
languageCode = "en-us"
title = "WapTug.Org"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 96 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/waptug"
  instagram = ""
  youtube = "https://youtube.com/WapTugDotOrg"
  github = "https://github.com/waptug"
  gitlab = "https://gitlab.com/waptug"
  linkedin = "https://linkedin.com/in/geekzonebooks"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 250
  disqusShortname = "waptug"
  HUGO_ENV="production"
  show_reading_time= true
  site_logo = "images/logo-small.png"
